export const connectionConfigs = 'connectionConfigs'
export const connectionDetail = 'connectionDetail'
export const connectionRegistry = 'connectionRegistry'
export const mainTable = 'mainTable'
export const queryTable = 'queryTable'
export const headerNavigation = 'headerNavigation'
